// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRL3r7XCUJBft9Z6D_DzDTw7E95KVWl9Q',
    appId: '1:42609036285:web:3640090918b518bb6f6794',
    messagingSenderId: '42609036285',
    projectId: 'myportfolio-afa4c',
    authDomain: 'myportfolio-afa4c.firebaseapp.com',
    storageBucket: 'myportfolio-afa4c.appspot.com',
    measurementId: 'G-G15MQ6XEG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPWKfFeTyziDTh-ah7dq9gh49h12Cug9s',
    appId: '1:42609036285:android:8034b9690e3f70436f6794',
    messagingSenderId: '42609036285',
    projectId: 'myportfolio-afa4c',
    storageBucket: 'myportfolio-afa4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-riLkgRJcY328FbV4oFzRSLWomxs2FqA',
    appId: '1:42609036285:ios:c4a89c64e9339c506f6794',
    messagingSenderId: '42609036285',
    projectId: 'myportfolio-afa4c',
    storageBucket: 'myportfolio-afa4c.appspot.com',
    iosBundleId: 'com.example.myPortfolioWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-riLkgRJcY328FbV4oFzRSLWomxs2FqA',
    appId: '1:42609036285:ios:c4a89c64e9339c506f6794',
    messagingSenderId: '42609036285',
    projectId: 'myportfolio-afa4c',
    storageBucket: 'myportfolio-afa4c.appspot.com',
    iosBundleId: 'com.example.myPortfolioWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRL3r7XCUJBft9Z6D_DzDTw7E95KVWl9Q',
    appId: '1:42609036285:web:3e6c475080a5c31b6f6794',
    messagingSenderId: '42609036285',
    projectId: 'myportfolio-afa4c',
    authDomain: 'myportfolio-afa4c.firebaseapp.com',
    storageBucket: 'myportfolio-afa4c.appspot.com',
    measurementId: 'G-C6SWB4T5V1',
  );
}
